/*
 * DisclaimerPanel.java
 *
 * The initial GUI ensuring the user has read and agreed to any terms.
 *
 * @author Michael Drayson
 * @version 1.0
 */

package drayson.weboca.gui;

import org.netbeans.spi.wizard.WizardPage;
import java.awt.Component;

public class PreAdvancedPanel extends WizardPage {
    
    /**
     * Creates new form DisclaimerPanel using the Wizard framework
     */
    public PreAdvancedPanel() {
        super("PreAdvancedPanel", "PreAdvancedPanel");         // Passes parameters to the super class
        initComponents();                          // Initialises all components on the page
        
        // Set the state "PreAdvancedChosen" in the wizard to false
        putWizardData("PreAdvancedChosen", "false");
                
        // Set the state "saved" in the wizard to false
        putWizardData("saved", "false");
        
        // Set the state "AdditionalParam" in the wizard to empty
        putWizardData("AdditionalParam", "");
    }
    
    /**
     * Returns the description of this GUI form
     *
     * @return The description of this form
     */
    public static String getDescription() {
        
        return "Pre Advanced Panel";
    }
    
    
   /**
     * A class to enable or disable all advanced features on the page when the
     * advanced box is ticked / unticked.
     */
    public void advancedClicked()
    {
        if (advancedBox.isSelected() == false)
        {
            putWizardData("PreAdvancedChosen", "false");
            searchParams.setEnabled(false);
            corpusSize.setEnabled(false);
        }
        
        if (advancedBox.isSelected() == true)
        {
            putWizardData("PreAdvancedChosen", "true");
            
            // Reset the state "saved" in the wizard to false
            putWizardData("saved", "false");
            searchParams.setEnabled(true);
            corpusSize.setEnabled(true);
        }
    }

    
    // The following code stops the page from continuing until a condition is met!
    protected String validateContents (Component component, Object o) 
    {
    
        if (advancedBox.isSelected())
        {
            if (getWizardData("saved") == "false")
            {
                return "You must save the advanced settings before continuing... ";
            }
        }
        
        return null;

    }
    


    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        grpBuildType = new javax.swing.ButtonGroup();
        advancedBox = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        searchParams = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        corpusSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        advancedBox.setText("Enable Advanced Options");
        advancedBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        advancedBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        advancedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreAdvancedPanel.this.actionPerformed(evt);
            }
        });

        jLabel1.setText("Additional search parameters");

        searchParams.setEnabled(false);
        searchParams.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchParamsFocusLost(evt);
            }
        });

        saveButton.setText("Save Settings!");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Limit the corpus size to ");

        corpusSize.setEnabled(false);
        corpusSize.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                corpusSizeFocusLost(evt);
            }
        });

        jLabel3.setText(" words           (leave blank for unlimited)");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 381, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(advancedBox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 139, Short.MAX_VALUE)
                        .add(saveButton))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                        .add(searchParams, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 229, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(corpusSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3))
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 381, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jSeparator3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(advancedBox)
                    .add(saveButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(searchParams, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(14, 14, 14)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(corpusSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14)
                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void corpusSizeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_corpusSizeFocusLost
       // Reset the state "saved" in the wizard to false
       putWizardData("saved", "false");
    }//GEN-LAST:event_corpusSizeFocusLost

    private void searchParamsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchParamsFocusLost
       // Reset the state "saved" in the wizard to false
       putWizardData("saved", "false");
    }//GEN-LAST:event_searchParamsFocusLost

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Set the state "saved" in the wizard to true as it's now been saved
        putWizardData("saved", "true");
        
        // Additional commands to save the state of all the additional options
        putWizardData("AdditionalParam", searchParams.getText());
        System.out.println("Saved " + searchParams.getText() + " to AdditionalParam");
    }//GEN-LAST:event_saveButtonActionPerformed

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
        advancedClicked();
    }//GEN-LAST:event_actionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox advancedBox;
    private javax.swing.JTextField corpusSize;
    private javax.swing.ButtonGroup grpBuildType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField searchParams;
    // End of variables declaration//GEN-END:variables
    
}
