/*
 * SummaryPanel.java
 *
 * Created on 15 August 2006, 02:56
 */

package drayson.weboca.gui;

import org.netbeans.spi.wizard.WizardPage;

/**
 *
 * @author  Andy Roberts
 */
public class SummaryPanel extends WizardPage {
    
    /**
     * Creates new form SummaryPanel
     */
    public SummaryPanel() {
        super("Summary", "Summary");
        initComponents();
        updateDetails();
    }
    
     protected void renderingPage() {
        updateDetails();
    }
    
    
    private void updateDetails() {
        
        String corpusFilename = (String)this.getWizardData("txtFilename");
        
        lblCorpusFilename.setText(corpusFilename);
        
        lblNumWords.setText((String)this.getWizardData("lblWordCount"));
        
        lblFilesize.setText((String)this.getWizardData("lblCurrentCorpusSize"));
        
        lblUrlsIncluded.setText((String)this.getWizardData("lblNumUrlsDownloaded"));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        lblCorpusFilename = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFilesize = new javax.swing.JLabel();
        lblNumWords = new javax.swing.JLabel();
        lblUrlsIncluded = new javax.swing.JLabel();

        jLabel1.setText("New corpus has been created and saved:");

        lblCorpusFilename.setText("corpus location");

        jLabel3.setText("Details");

        jLabel6.setText("Corpus file size:");

        jLabel5.setText("Number of words:");

        jLabel4.setText("URLs included:");

        lblFilesize.setText("jLabel7");

        lblNumWords.setText("jLabel7");

        lblUrlsIncluded.setText("jLabel7");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(lblCorpusFilename))
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(jLabel1)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .add(10, 10, 10)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel5)
                                        .add(jLabel4)
                                        .add(jLabel6))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(lblFilesize)
                                        .add(lblUrlsIncluded)
                                        .add(lblNumWords))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 64, Short.MAX_VALUE))))
                        .addContainerGap(190, Short.MAX_VALUE))
                    .add(jLabel3)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblCorpusFilename)
                .add(31, 31, 31)
                .add(jLabel3)
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblUrlsIncluded))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(lblNumWords))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(lblFilesize))
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCorpusFilename;
    private javax.swing.JLabel lblFilesize;
    private javax.swing.JLabel lblNumWords;
    private javax.swing.JLabel lblUrlsIncluded;
    // End of variables declaration//GEN-END:variables
    
}
